### ISSUE TITLE
Type checking before passing the arguments to Extension:Variables

### ISSUE THREAD

**Issue by ghost** [Liquipedia/VariablesLua#2]
Currently the extension does not perform any type checking, which leads to
1. Boolean values get converted to `1` or `void`.
2. nil, tables and functions not being stored without raising an error.
3. Un-catchable exceptions when no variable name is given.

Thus I would suggest adding some typechecking using either the `libraryUtil` or just basic assertations to make the extension behave in more expectable ways and at least warn the user when storing these values.

**Comment by FO-nTTaX** [comment]
I suppose due to how wikicode works technically everything should be transformed to strings, right?

**Comment by ghost** [comment]
Yes, thats what Extension:Variables does with numbers. It can't do that for all the other types though.

EDIT: That either leads to an empty string being stored or an exception like this: `[9e674d97978a971ce865c2d5] Exception caught: PPFrame_DOM::expand: Invalid parameter type` that can't ba caught using `pcall()`

**Comment by ghost** [comment]
I can't test it right now, but something like [this](https://gist.github.com/Litzsch/990a160d9ff99d2bfd1dd06b25d4e8ac) should do the job.

**Comment by FO-nTTaX** [comment]
That looks fairly well, however it breaks if there is no second parameter for mw.ext.VariablesLua.var

**Comment by FO-nTTaX** [comment]
I pushed what you used but also allowed nil for default values. Thanks a bunch for your help already, but does this work like it should now?

**Comment by ghost** [comment]
Ah the `{ 'string', 'number' }, true )` needs to be replaced by `{ 'nil', 'string', 'number' } )`

**Comment by FO-nTTaX** [comment]
Yeah just did that

**Comment by ghost** [comment]
You missed the ones for `vardefine` and `vardefineecho`, but apart from that it should work much better now. As I said I can't really test it right now due to being on vacation (I tested the varexists thing [here](https://sandbox.semantic-mediawiki.org/wiki/)), but it looks good to me.

**Comment by FO-nTTaX** [comment]
I guess I could do that there too, just pushed that too

**Comment by ghost** [comment]
Yeah looks good to me now. Thanks for the quick response and fix!

**Comment by FO-nTTaX** [comment]
No problem, thanks again for your help with it
